/** IrisFiles - HTML to PDF page UI. */
import {htmlFileToPdf} from './html-pdf-engine.js';
import {validateFile,formatSize,downloadBlob} from './converter.js';
import {showPersistentNotice} from './notice-ui.js';
let file=null;let dropZone,fileInput,fileList,actionBtn,clearBtn,result;
export function init(){dropZone=document.getElementById('drop-zone');fileInput=document.getElementById('file-input');fileList=document.getElementById('file-list');actionBtn=document.getElementById('action-btn');clearBtn=document.getElementById('clear-all');result=document.getElementById('html-pdf-result');if(!dropZone||!fileInput)return;dropZone.addEventListener('click',()=>fileInput.click());dropZone.addEventListener('dragover',e=>{e.preventDefault();dropZone.classList.add('dragover')});dropZone.addEventListener('dragleave',()=>dropZone.classList.remove('dragover'));dropZone.addEventListener('drop',e=>{e.preventDefault();dropZone.classList.remove('dragover');choose(e.dataTransfer.files)});fileInput.addEventListener('change',()=>{choose(fileInput.files);fileInput.value=''});actionBtn.addEventListener('click',run);clearBtn.addEventListener('click',clear);document.querySelectorAll('.faq-question').forEach(btn=>btn.addEventListener('click',()=>btn.parentElement.classList.toggle('open')))}
function choose(files){const candidate=Array.from(files).find(f=>/\.html?$/i.test(f.name)||f.type==='text/html');if(!candidate)return notice('Choose an HTML file.');try{validateFile(candidate)}catch(err){return notice(err.message)}file=candidate;fileList.innerHTML=`<div class="file-item"><div class="file-item__info"><div class="file-item__name">${esc(file.name)}</div><div class="file-item__meta">${formatSize(file.size)}</div></div></div>`;actionBtn.style.display=clearBtn.style.display='';result.innerHTML=''}
async function run(){if(!file)return;actionBtn.disabled=true;const old=actionBtn.textContent;try{const blob=await htmlFileToPdf(file,(p,status)=>actionBtn.textContent=`${status} ${p}%`);const name=file.name.replace(/\.html?$/i,'')+'.pdf';result.innerHTML=`<div class="file-item done"><div class="file-item__info"><div class="file-item__name">${esc(name)}</div><div class="file-item__meta">${formatSize(blob.size)}</div></div><div class="file-item__actions"><button id="html-pdf-download" class="btn btn--success">Download</button></div></div>`;result.querySelector('#html-pdf-download').onclick=()=>downloadBlob(blob,name)}catch(err){notice(err.message||'HTML conversion failed.')}finally{actionBtn.disabled=false;actionBtn.textContent=old}}
function clear(){file=null;fileList.innerHTML='';result.innerHTML='';actionBtn.style.display=clearBtn.style.display='none'}function notice(msg){showPersistentNotice(dropZone,msg,{id:'html-pdf-notice',kind:'warning'})}function esc(v){const d=document.createElement('div');d.textContent=v;return d.innerHTML}
