/**
 * Baseline TIFF decoder for IrisFiles. Runs entirely in the browser.
 * Classic TIFF (II/MM), strips, chunky samples, uncompressed/LZW/Deflate/
 * PackBits, bilevel/grayscale/palette/RGB/RGBA/CMYK, 1/2/4/8/16-bit samples.
 */
const TYPE_SIZE={1:1,2:1,3:2,4:4,5:8,6:1,7:1,8:2,9:4,10:8,11:4,12:8};
function fail(m='Unsupported or malformed TIFF'){throw new Error(m)}
function range(o,n,total){if(!Number.isSafeInteger(o)||!Number.isSafeInteger(n)||o<0||n<0||o+n>total)fail('TIFF points outside the file')}
function parse(buffer){
 const view=new DataView(buffer),bytes=new Uint8Array(buffer);if(bytes.length<8)fail('TIFF header is truncated');
 const marker=String.fromCharCode(bytes[0],bytes[1]),little=marker==='II';if(!little&&marker!=='MM')fail('Invalid TIFF byte order');
 const u16=o=>{range(o,2,bytes.length);return view.getUint16(o,little)},i16=o=>{range(o,2,bytes.length);return view.getInt16(o,little)},u32=o=>{range(o,4,bytes.length);return view.getUint32(o,little)},i32=o=>{range(o,4,bytes.length);return view.getInt32(o,little)};
 if(u16(2)!==42)fail('Only classic TIFF is supported');const ifd=u32(4);range(ifd,2,bytes.length);const count=u16(ifd);if(count>4096)fail('TIFF directory is too large');range(ifd+2,count*12+4,bytes.length);
 const tags=new Map();
 for(let i=0;i<count;i++){const e=ifd+2+i*12,tag=u16(e),type=u16(e+2),cnt=u32(e+4),size=TYPE_SIZE[type];if(!size||cnt>1e6)fail('Unsupported TIFF field');const len=size*cnt,off=len<=4?e+8:u32(e+8);range(off,len,bytes.length);const vals=[];
  for(let j=0;j<cnt;j++){const p=off+j*size;if(type===1||type===7)vals.push(bytes[p]);else if(type===3)vals.push(u16(p));else if(type===4)vals.push(u32(p));else if(type===6)vals.push(view.getInt8(p));else if(type===8)vals.push(i16(p));else if(type===9)vals.push(i32(p));else if(type===11)vals.push(view.getFloat32(p,little));else if(type===12)vals.push(view.getFloat64(p,little));else if(type===5||type===10){const a=type===5?u32(p):i32(p),b=type===5?u32(p+4):i32(p+4);vals.push(b?a/b:0)}else if(type===2)vals.push(bytes[p])}
  tags.set(tag,type===2?[String.fromCharCode(...vals).replace(/\0+$/,'')]:vals)
 }
 return{bytes,little,one:(t,d)=>tags.has(t)?tags.get(t)[0]:d,many:(t,d=[])=>tags.has(t)?tags.get(t):d,assertRange:(o,n)=>range(o,n,bytes.length)}
}
function packBits(input,expected){const out=new Uint8Array(expected);let s=0,d=0;while(s<input.length&&d<expected){let n=input[s++];if(n>127)n-=256;if(n>=0){const c=n+1;if(s+c>input.length||d+c>expected)fail('Truncated PackBits strip');out.set(input.subarray(s,s+c),d);s+=c;d+=c}else if(n>=-127){const c=1-n;if(s>=input.length||d+c>expected)fail('Truncated PackBits run');out.fill(input[s++],d,d+c);d+=c}}if(d!==expected)fail('PackBits strip decoded to the wrong size');return out}
function lzw(input,expected){let bit=0,width=9,table,next;const reset=()=>{table=new Array(4096);for(let i=0;i<256;i++)table[i]=Uint8Array.of(i);next=258;width=9};const code=()=>{if(bit+width>input.length*8)return null;let c=0;for(let i=0;i<width;i++){const p=bit+i;c=(c<<1)|((input[p>>3]>>(7-(p&7)))&1)}bit+=width;return c};reset();const out=new Uint8Array(expected);let pos=0,prev=null;while(pos<expected){const c=code();if(c===null)break;if(c===256){reset();prev=null;continue}if(c===257)break;let entry;if(c<next&&table[c])entry=table[c];else if(c===next&&prev){entry=new Uint8Array(prev.length+1);entry.set(prev);entry[prev.length]=prev[0]}else fail('Invalid TIFF LZW code');if(pos+entry.length>expected)fail('TIFF LZW strip is too large');out.set(entry,pos);pos+=entry.length;if(prev&&next<4096){const joined=new Uint8Array(prev.length+1);joined.set(prev);joined[prev.length]=entry[0];table[next++]=joined;if(width<12&&next===(1<<width)-1)width++}prev=entry}if(pos!==expected)fail('TIFF LZW strip decoded to the wrong size');return out}
async function deflate(input,expected){if(typeof DecompressionStream==='undefined')fail('Deflate-compressed TIFF is not supported in this browser');let buf;try{buf=await new Response(new Blob([input]).stream().pipeThrough(new DecompressionStream('deflate'))).arrayBuffer()}catch{fail('Could not decompress TIFF strip')}const out=new Uint8Array(buf);if(out.length!==expected)fail('Deflate strip decoded to the wrong size');return out}
async function decompress(input,c,expected){if(c===1){if(input.length<expected)fail('TIFF strip is truncated');return input.slice(0,expected)}if(c===5)return lzw(input,expected);if(c===8||c===32946)return deflate(input,expected);if(c===32773)return packBits(input,expected);fail('Unsupported TIFF compression ('+c+')')}
function reverseByte(v){v=((v&0x55)<<1)|((v>>>1)&0x55);v=((v&0x33)<<2)|((v>>>2)&0x33);return((v<<4)|(v>>>4))&255}
function predictor(bytes,p,w,rows,samples,bits,little){if(p===1)return bytes;if(p!==2||!bits.every(b=>b===bits[0])||![8,16].includes(bits[0]))fail('Unsupported TIFF predictor ('+p+')');const depth=bits[0],rowBytes=w*samples*(depth/8);if(depth===8){for(let y=0;y<rows;y++){const row=y*rowBytes;for(let i=samples;i<rowBytes;i++)bytes[row+i]=(bytes[row+i]+bytes[row+i-samples])&255}return bytes}const view=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength),count=w*samples;for(let y=0;y<rows;y++){const row=y*rowBytes;for(let s=samples;s<count;s++){const at=row+s*2,pr=row+(s-samples)*2;view.setUint16(at,(view.getUint16(at,little)+view.getUint16(pr,little))&65535,little)}}return bytes}
function to8(v,b){if(b===8)return v;if(b===16)return v>>>8;return Math.round(v*255/((1<<b)-1))}
function sample(bytes,bit,bits,little){if(bits===8)return bytes[bit>>3];if(bits===16){const o=bit>>3;return little?bytes[o]|(bytes[o+1]<<8):(bytes[o]<<8)|bytes[o+1]}let v=0;for(let i=0;i<bits;i++){const p=bit+i;v=(v<<1)|((bytes[p>>3]>>(7-(p&7)))&1)}return v}
export async function decodeTiffToRgba(buffer,{maxPixels=100_000_000}={}){
 const r=parse(buffer),one=r.one,many=r.many,w=Number(one(256,0)),h=Number(one(257,0));if(!Number.isSafeInteger(w)||!Number.isSafeInteger(h)||w<=0||h<=0)fail('Invalid TIFF dimensions');const px=w*h;if(!Number.isSafeInteger(px)||px>maxPixels)fail('TIFF is too large ('+w+'x'+h+').');
 const compression=Number(one(259,1)),photo=Number(one(262,1)),samples=Number(one(277,photo===2?3:photo===5?4:1)),planar=Number(one(284,1)),pred=Number(one(317,1)),orientation=Number(one(274,1)),fill=Number(one(266,1)),formats=many(339,[1]);
 if(planar!==1)fail('Planar TIFF images are not supported yet');if(formats.some(f=>f!==1))fail('Only unsigned-integer TIFF samples are supported');if(![0,1,2,3,5].includes(photo))fail('Unsupported TIFF color model ('+photo+')');if(![1,2].includes(fill))fail('Unsupported TIFF fill order ('+fill+')');
 let bits=many(258,[1]).map(Number);if(bits.length===1&&samples>1)bits=Array(samples).fill(bits[0]);if(bits.length!==samples||bits.some(b=>![1,2,4,8,16].includes(b)))fail('Unsupported TIFF bit depth');if(photo===2&&samples<3)fail('Invalid RGB TIFF');if(photo===5&&samples<4)fail('Invalid CMYK TIFF');if((photo===2||photo===5)&&!bits.every(b=>b===bits[0]))fail('Mixed TIFF channel depths are not supported');
 const bpp=bits.reduce((a,b)=>a+b,0),rowBytes=Math.ceil(w*bpp/8),rowsPer=Math.max(1,Number(one(278,h))),offsets=many(273).map(Number),counts=many(279).map(Number);if(!offsets.length||offsets.length!==counts.length)fail('Invalid TIFF strip table');const decoded=new Uint8Array(rowBytes*h);let row=0;
 for(let i=0;i<offsets.length&&row<h;i++){const rows=Math.min(rowsPer,h-row),expected=rowBytes*rows;r.assertRange(offsets[i],counts[i]);let strip=await decompress(r.bytes.subarray(offsets[i],offsets[i]+counts[i]),compression,expected);strip=predictor(strip,pred,w,rows,samples,bits,r.little);if(fill===2&&bpp<8*samples){strip=strip.slice();for(let j=0;j<strip.length;j++)strip[j]=reverseByte(strip[j])}decoded.set(strip,row*rowBytes);row+=rows}if(row!==h)fail('TIFF is missing image rows');
 const map=many(320);if(photo===3){const n=1<<bits[0];if(map.length<n*3)fail('Invalid TIFF color map')}const extra=many(338),base=photo===2?3:photo===5?4:1,alphaIndex=samples>base?base:-1,assoc=alphaIndex>=0&&extra[0]===1,rgba=new Uint8ClampedArray(w*h*4);
 for(let y=0;y<h;y++){const rowBit=y*rowBytes*8;for(let x=0;x<w;x++){let bit=rowBit+x*bpp;const vals=[];for(let ch=0;ch<samples;ch++){vals.push(sample(decoded,bit,bits[ch],r.little));bit+=bits[ch]}let rr=0,g=0,b=0;if(photo===0||photo===1){let q=to8(vals[0],bits[0]);if(photo===0)q=255-q;rr=g=b=q}else if(photo===2){rr=to8(vals[0],bits[0]);g=to8(vals[1],bits[1]);b=to8(vals[2],bits[2])}else if(photo===3){const idx=vals[0],n=1<<bits[0];rr=map[idx]>>>8;g=map[n+idx]>>>8;b=map[2*n+idx]>>>8}else{const c=to8(vals[0],bits[0]),m=to8(vals[1],bits[1]),yy=to8(vals[2],bits[2]),k=to8(vals[3],bits[3]);rr=255-Math.min(255,c+k);g=255-Math.min(255,m+k);b=255-Math.min(255,yy+k)}let a=alphaIndex>=0?to8(vals[alphaIndex],bits[alphaIndex]):255;if(assoc&&a>0&&a<255){rr=Math.min(255,Math.round(rr*255/a));g=Math.min(255,Math.round(g*255/a));b=Math.min(255,Math.round(b*255/a))}const o=(y*w+x)*4;rgba[o]=rr;rgba[o+1]=g;rgba[o+2]=b;rgba[o+3]=a}}
 return{width:w,height:h,rgba,orientation}
}
